# Generated by Django 4.0.2 on 2022-05-17 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_membercar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ride_date', models.DateField(default=datetime.date.today)),
                ('ride_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('ride_end_time', models.TimeField(default=django.utils.timezone.now)),
                ('seats_offered', models.PositiveIntegerField(default=0, null=True)),
                ('contribution_per_head', models.PositiveIntegerField(default=0, null=True)),
                ('member_car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.membercar')),
                ('source_city_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.city')),
            ],
        ),
    ]
