# Generated by Django 4.0.2 on 2022-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
