# Generated by Django 4.0.2 on 2022-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_ride_destination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_registration_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
