# Generated by Django 4.0.2 on 2022-05-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_car_car_registration_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.member')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ride')),
            ],
        ),
    ]
